#ifndef OHOS_LITEOS_ESP32P4_PORT_H
#define OHOS_LITEOS_ESP32P4_PORT_H

#ifndef OHOS_LITEOS_ESP32P4_TRACE
#define OHOS_LITEOS_ESP32P4_TRACE 0
#endif

#ifndef OHOS_LITEOS_ESP32P4_SMOKE_TEST
#define OHOS_LITEOS_ESP32P4_SMOKE_TEST 1
#endif

#ifndef OHOS_LITEOS_ESP32P4_SMOKE_LOG_EVERY
#define OHOS_LITEOS_ESP32P4_SMOKE_LOG_EVERY 10U
#endif

#ifndef OHOS_LITEOS_ESP32P4_IDLE_STACK_SIZE
#define OHOS_LITEOS_ESP32P4_IDLE_STACK_SIZE 0x2000U
#endif

#ifndef OHOS_LITEOS_ESP32P4_QUEUE_SMOKE_PERIOD_MS
#define OHOS_LITEOS_ESP32P4_QUEUE_SMOKE_PERIOD_MS 200U
#endif

#ifndef OHOS_LITEOS_ESP32P4_QUEUE_MAGIC_BASE
#define OHOS_LITEOS_ESP32P4_QUEUE_MAGIC_BASE 0xD7000000U
#endif

#if OHOS_LITEOS_ESP32P4_TRACE
#define OHOS_PORT_TRACE_PRINTF(...) esp_rom_printf(__VA_ARGS__)
#else
#define OHOS_PORT_TRACE_PRINTF(...) do { } while (0)
#endif

#endif /* OHOS_LITEOS_ESP32P4_PORT_H */
